AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  MyPolicy: 
    Type: AWS::IoT::Policy
    Properties: 
      PolicyName: "WiFiSmartDeviceAppPolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "iot:Connect"
            Resource: 
              - "*"
          - 
            Effect: "Allow"
            Action: 
              - "iot:Publish"
            Resource: 
              - "*"
          - 
            Effect: "Allow"
            Action: 
              - "iot:Subscribe"
            Resource: 
              - "*"
          - 
            Effect: "Allow"
            Action: 
              - "iot:Receive"
            Resource: 
              - "*"
